---
printWidth: 100
proseWrap: always
overrides:
  - files: '**/*.{yaml,yml}'
    options:
      printWidth: 120
      singleQuote: false
      tabWidth: 2
  - files: '**/*.md'
    options:
      proseWrap: always
